/**
 * The MIT License (MIT)
 * 
 * Copyright (c) 2022 Antoine Maleyrie
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

// Includes --------------------------------------------------------------------
#include "stm32g0xx_ll_system.h"
#include "stm32g0xx_ll_utils.h"
#include "stm32g0xx_ll_bus.h"
#include "stm32g0xx_ll_rcc.h"
#include "stm32g0xx_ll_pwr.h"
#include "stm32g0xx_ll_gpio.h"
#include "stm32g0xx_ll_exti.h"

#include "nucleo_g071x.h"

// Private prototype functions --------------------------------------------------
void _systemClock_Config();

// Implemented functions -------------------------------------------------------

/**
 * @brief Init clock, power and main gpio of the board.
 * @note A part of this function is generated by stm32CubeMx.
 */
void boardInit()
{
    // Reset of all peripherals, Initializes the Flash interface and the Systick.
    LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG);
    LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);
    
    // Disable the internal Pull-Up in Dead Battery pins of UCPD peripheral
    LL_SYSCFG_DisableDBATT(LL_SYSCFG_UCPD1_STROBE | LL_SYSCFG_UCPD2_STROBE);
  
    // Init clock
    _systemClock_Config();
    LL_Init1msTick(SystemCoreClock);
    
    //// Enable clock for all gpio
    //LL_IOP_GRP1_EnableClock(LL_IOP_GRP1_PERIPH_ALL);
    
    ///* -2- Connect External Line to the GPIO*/
    //LL_EXTI_SetEXTISource(LL_EXTI_CONFIG_PORTC, LL_EXTI_CONFIG_LINE13);
    //LL_EXTI_SetEXTISource(LL_EXTI_CONFIG_PORTB, LL_EXTI_CONFIG_LINE7);
    
    ///*-3- Enable a falling trigger EXTI line 13 Interrupt */
    //LL_EXTI_EnableIT_0_31(LL_EXTI_LINE_13);
    //LL_EXTI_EnableFallingTrig_0_31(LL_EXTI_LINE_13);
    ///*-3- Enable a falling trigger EXTI line 7 Interrupt */
    //LL_EXTI_EnableIT_0_31(LL_EXTI_LINE_7);
    //LL_EXTI_EnableFallingTrig_0_31(LL_EXTI_LINE_7);
    
    ///*-4- Configure NVIC for EXTI4_15_IRQn */
    //NVIC_EnableIRQ(EXTI4_15_IRQn); 
    //NVIC_SetPriority(EXTI4_15_IRQn, 0);
}

/**
 * @brief Init the system clock.
 * @note This function is generated by stm32CubeMx.
 */
void _systemClock_Config(void)
{
    LL_FLASH_SetLatency(LL_FLASH_LATENCY_2);
    while(LL_FLASH_GetLatency() != LL_FLASH_LATENCY_2)
    {
    }
    
    /* HSI configuration and activation */
    LL_RCC_HSI_Enable();
    while(LL_RCC_HSI_IsReady() != 1)
    {
    }
    
    LL_PWR_EnableBkUpAccess();
    /* LSE configuration and activation */
    LL_RCC_LSE_SetDriveCapability(LL_RCC_LSEDRIVE_LOW);
    LL_RCC_LSE_Enable();
    while(LL_RCC_LSE_IsReady() != 1)
    {
    }
    
    /* Main PLL configuration and activation */
    LL_RCC_PLL_ConfigDomain_SYS(LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_1, 8, LL_RCC_PLLR_DIV_2);
    LL_RCC_PLL_Enable();
    LL_RCC_PLL_EnableDomain_SYS();
    while(LL_RCC_PLL_IsReady() != 1)
    {
    }
    
    /* Set AHB prescaler*/
    LL_RCC_SetAHBPrescaler(LL_RCC_SYSCLK_DIV_1);
    
    /* Sysclk activation on the main PLL */
    LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL);
    while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL)
    {
    }
    
    /* Set APB1 prescaler*/
    LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_1);
    /* Update CMSIS variable (which can be updated also through SystemCoreClockUpdate function) */
    LL_SetSystemCoreClock(64000000);
}
